name: Deploy Staging

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 'pypy-3.6' ]
    name: deploy on heroku
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sapo-staging-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: "https://github.com/heroku/heroku-buildpack-python#latest"
          healthcheck: "https://sapo-staging-api.herokuapp.com/"
          delay: 5
        env:
          HD_FLASK_ENV: ${{secrets.FLASK_ENV}}
          HD_DB_DIALECT: ${{secrets.DB_DIALECT}}
          HD_DB_HOST: ${{secrets.DB_HOST_STAGING}}
          HD_DB_PORT: ${{secrets.DB_PORT_STAGING}}
          HD_DB_NAME: ${{secrets.DB_NAME_STAGING}}
          HD_DB_USER: ${{secrets.DB_USER_STAGING}}
          HD_DB_PASS: ${{secrets.DB_PASS_STAGING}}